#!/bin/bash

# getopt
SHORT_OPTS="ar"
LONG_OPTS="archive,rsync,only-archive"
PARSED_OPTS=$(getopt --options $SHORT_OPTS --longoptions $LONG_OPTS --name "$0" -- "$@")
if [[ $? -ne 0 ]]; then
  echo "Wrong Input!" >&2
  exit 2
fi
eval set -- "$PARSED_OPTS" # Strings after `--` will be treated as parameters

unset SHORT_OPTS LONG_OPTS PARSED_OPTS

# reading options
mode=""
only_archive=""

while true; do
  case $1 in
    -a|--archive)
      if [[ -z $mode ]]; then
        mode="archive"
      elif [[ $mode != "archive" ]]; then
        echo "Sorry, we can only do same type of things at once." >&2
        exit 2
      fi
      shift
      ;;
    -r|--rsync)
      if [ -z $mode ]; then
        mode="rsync"
      elif [[ $mode != "rsync" ]]; then
        echo "Sorry, we can only do same type of things at once." >&2
        exit 2
      fi
      shift
      ;;
    --only-archive)
      if [[ $mode == "rsync" ]]; then
        only_archive="Y"
      else
        echo "Option '--only-archive' should come after '-r|--rsync'" >&2
        exit 2
      fi
      shift
      ;;
    --)
      shift
      break
      ;;
    *)
      echo "Wrong Input!" >&2
      exit 2
      ;;
  esac
done

# reading parameters
